spring:
  datasource:
    password: sharma
    url: jdbc:mysql://localhost:3306/INSURANCE_DETAILS
    username: root
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
